nmap('<C-J>', '<C-W><C-J>')
nmap('<C-K>', '<C-W><C-K>')
nmap('<C-L>', '<C-W><C-L>')
nmap('<C-H>', '<C-W><C-H>')
nmap('<Leader><Leader>', '<C-^>')
nmap('<Leader>sv', ':source $MYVIMRC<CR>')
nmap('<ESC>', ':noh<CR>')
