---
model: "ollama_chat/gpt-oss:20b"
weak-model: "ollama_chat/gpt-oss:20b"

auto-commits: false
no-auto-commits: true
yes-always: false

user-input-color: "#98BB6C"
tool-error-color: "#C34043"
tool-warning-color: "#DCA561"
assistant-output-color: "#7E9CD8"

dark-mode: true
pretty: true
