alias sudo='sudo '
alias vim='nvim'
alias vi='nvim'
alias view='nvim -R'
alias vimdiff='nvim -d'
alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gco='git checkout'
alias gd='git diff'
alias gdc='git diff --cached'
alias gr='git remote'
alias gs='git status'

bind -x '"\C-f": dir=$(find * -type d | fzf) && cd $dir'
bind -x '"\C-p": dir=$(find * -type d | fzf) && cd $dir && vim .'
