#
# GENERAL
#
set -g default-terminal "tmux-256color"
# true color
set-option -gas terminal-overrides "*:Tc"
set-option -gas terminal-overrides "*:RGB"
# undercurl support
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
# underscore colours - needs tmux-3.0
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
# zen-mode
set-option -g allow-passthrough on
set -s escape-time 0
# mouse
set -g mouse off
set -g base-index 1
set-window-option -g pane-base-index 1
# act like vim
setw -g mode-keys vi
# renumber windows sequentially after closing any of them
set -g renumber-windows on
# refresh 'status-left' and 'status-right' more often
set -g status-interval 5
# increase scrollback lines
set -g history-limit 50000
# tmux messages are displayed for 4 seconds
set -g display-time 4000
# focus events enabled for terminals that support them
set -g focus-events on
# notify
set -g @tnotify-verbose 'on'
set -g @tnotify-verbose-msg "Tmux task complete: [#S] #I:#W[#P]"

#
# KEYS
#
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# collapsed window preview
bind-key 'w' choose-tree -Zs
# reload ~/.tmux.conf using PREFIX r
bind r source-file ~/.tmux.conf \; display "Tmux config reloaded"
# make copy mode more intuitive
bind -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection
bind-key -T copy-mode-vi Y send -X copy-selection
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection
# don't suspend-client
unbind-key C-z
unbind-key C-S-n
unbind-key C-S-p
# Move panes
bind-key -n 'C-Up' 'swap-pane -D'
bind-key -n 'C-Down' 'swap-pane -U'
bind-key -n 'C-Left' 'swap-pane -D'
bind-key -n 'C-Right' 'swap-pane -U'
# resize panes more easily
bind-key C-< resize-pane -L 5
bind-key C-> resize-pane -R 5
bind-key C-- resize-pane -D 5
bind-key C-+ resize-pane -U 5
# use <prefix> s for horizontal split
bind-key s split-window -v -c '#{pane_current_path}'
# use <prefix> v for vertical split
bind-key v split-window -h -c '#{pane_current_path}'

# notes
bind-key -r n run-shell "tmux neww -n \"notes\" ~/.config/tmux/notes.zsh"
bind-key -r t run-shell "tmux neww -n \"todo\" ~/.config/tmux/todo.zsh"
bind-key -r p run-shell "tmux neww -n \"sessionizer\" ~/.config/tmux/sessionizer.sh"

source-file ~/.config/tmux/kanagawa.conf

#
# Plugins
#
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'mrjones2014/smart-splits.nvim'
# set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'rickstaa/tmux-notify'
set -g @plugin 'Morantron/tmux-fingers'

run '~/.tmux/plugins/tpm/tpm'
