local opencode_prefix = "<leader>a"

local function llm_warning()
	local buf = vim.api.nvim_get_current_buf()
	local line = vim.fn.getpos("v")[2]

	local comment_prefix = vim.bo[buf].commentstring
	if comment_prefix == "" then
		comment_prefix = "//"
	end

	local start_comment = comment_prefix:gsub("%%s", "")
	local text = "warn: this code was generated by an LLM, please review"
	local comment = start_comment .. text
	vim.api.nvim_buf_set_lines(buf, line - 1, line - 1, false, { comment })
end

return {
	"NickvanDyke/opencode.nvim",
	dependencies = {
		-- Recommended for `ask()` and `select()`.
		-- Required for `snacks` provider.
		---@module 'snacks' <- Loads `snacks.nvim` types for configuration intellisense.
		{
			"folke/snacks.nvim",
			opts = {
				input = {},
				picker = {},
				terminal = {},
			},
		},
	},
	config = function()
		---@type opencode.Opts
		vim.g.opencode_opts = {
			-- Your configuration, if any — see `lua/opencode/config.lua`, or "goto definition".
		}

		-- Required for `opts.events.reload`.
		vim.o.autoread = true
	end,
	keys = {
		{
			opencode_prefix .. "e",
			function()
				require("opencode").toggle()
			end,
			mode = { "n", "x", "v" },
			desc = "opencode: toggle",
		},
		{
			opencode_prefix .. "a",
			function()
				require("opencode").ask("Explain @this and its context", { submit = true })
			end,
			mode = { "n", "x", "v" },
			desc = "opencode: ask",
		},
		{
			opencode_prefix .. "i",
			function()
				llm_warning()
				require("opencode").ask("Implement @this", { submit = true })
			end,
			mode = { "n", "x", "v" },
			desc = "opencode: implement",
		},
	},
}
