require('plugins')
require('settings')
require('utility')
require('indent-line')
require('gitgutter')
require('lsp-config')
-- require('ale')
require('telescope-config')
require('mappings')
require('fugitive')
require('treesitter')
require('harpoon-config')
